### ISSUE TITLE
Why not just use youtube-dl directly?

### ISSUE THREAD

**Issue by paraschetal** [CodeMaxx/SyncYoutube#1]
youtube-dl can be directly used to scrape the videos of entire channels from youtube. The use case of this tool seems redundant, especially given that the user has to install youtube-dl anyways. Or am I missing something?

**Comment by CodeMaxx** [comment]
In principal you can use youtube-dl. But I have found that script downloads stuff faster due to less overheads. What youtube-dl does is scrap the whole channel to find videos and then downloads it one by one. SyncYoutube on the other hand uses Youtube's api to get stuff which is faster(Not a lot of difference but yeah some people may care about it). 

The **major difference** is though that `youtube-dl` will dump everything into one place. `SyncYoutube` on the other hand will create playlists for you and arrange videos into folders which is a good enough incentive to use this script.
I hope this helps. 😄

**Comment by paraschetal** [comment]
+1 for the API usage instead of scraping the page.
However, youtube-dl does not dump everything into one place. You can specify the output template. See the 4th example [here](https://github.com/rg3/youtube-dl/#output-template-examples). It's pretty similar to the output of SyncYoutube. Further, it's easily customizable.

**Comment by CodeMaxx** [comment]
Oh didn't know about that. 
Actually that feature got added to youtube-dl after I made SyncYoutube.

**Comment by paraschetal** [comment]
Are you sure? I think it was [there](https://github.com/rg3/youtube-dl/tree/2016.01.01#filesystem-options) before too :smile: .

**Comment by CodeMaxx** [comment]
Not really sure, but the line in readme you linked me to got added afterwards.
